name: Docker Image CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Build Updates of Pull Requests
              run: |
                rootdir="$(pwd)"
                built="$rootdir/done.txt"
                touch "$built"
                for d in $(ls | sort -h -r); do
                    if [ -d "$d" ]; then
                        cd "$d"
                        program=$(echo "$d" | cut -d: -f 1)
                        if grep -Fxq "$program" "$built"; then
                            # Already latest version already built
                        else
                            if [ -f Dockerfile ]; then
                                # The directory name *is* the tag and version
                                docker build . --file Dockerfile --tag "$d"
                            fi
                            echo "$program" >> "$built"
                        fi
                        cd "$rootdir"
                    fi
                done
