name: Docker Image CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build all Docker images
              run: |
                rootdir="$(pwd)"
                for d in $(ls | sort -h -r); do
                    if [ -d "$d" ]; then
                        cd "$d"
                        program=$(echo "$d" | cut -d: -f 1)
                        echo $program
                        echo $d
                        if ! grep -Fxq "$program" "$built"; then
                            # No version built yet
                            if [ -f Dockerfile ]; then
                                # The directory name *is* the tag and version
                                echo $d
                                docker build --tag ghcr.io/${{ steps.repo-owner.outputs.repo-owner }}/$d .
                            fi
                        fi
                    fi
                done
