name: Docker Image CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build all Docker images
              run: |
                rootdir="$(pwd)"
                for d in $(ls | sort -h -r); do
                    echo $d
                    cd $d
                    ls
                done
