name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
          rootdir="$(pwd)"
                pwd
                built="$rootdir/done.txt"
                touch "$built"
                for d in $(ls | sort -h -r); do
                    if [ -d "$d" ]; then
                        cd "$d"
                        program=$(echo "$d" | cut -d: -f 1)
                        if ! grep -Fxq "$program" "$built"; then
                            # No version built yet
                            if [ -f Dockerfile ]; then
                                # The directory name *is* the tag and version
                                docker build . --file Dockerfile --tag "$d"
                            fi
                            echo "$program" >> "$built"
                        fi
                        cd "$rootdir"
                    fi
                done
    - name: Docker Push
      run: | 
          docker push $DOCKER_USER/$rootdir
      
