name: Docker Image CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  push:
    name: Build and push

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${GITHUB_ACTOR,,} --password-stdin ghcr.io

      - name: Repository owner needs to be lowercase
        id: repo-owner
        run: |
          REPO_OWNER=${{ github.repository_owner }}
          echo "::set-output name=repo-owner::${REPO_OWNER,,}"
      - name: Build orca image
        run: |
          rootdir="$(pwd)"
          built="$rootdir/done.txt"
          touch "$built"
          for d in $(ls | sort -h -r); do
                    if [ -d "$d" ]; then
                        cd "$d"
                        program=$(echo "$d" | cut -d: -f 1)
                        if ! grep -Fxq "$program" "$built"; then
                            # No version built yet
                            if [ -f Dockerfile ]; then
                                # The directory name *is* the tag and version
                                IMAGE_NAME=$d
                                docker build --tag ghcr.io/${{ steps.repo-owner.outputs.repo-owner }}/$IMAGE_NAME .
                            fi
                            echo "$program" >> "$built"
                        fi
                        cd "$rootdir"
                    fi
            done
      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ steps.repo-owner.outputs.repo-owner }}/$rootdir
