name: Docker Image CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    push:
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Log into DockerHub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}"
            - name: Repository owner needs to be lowercase
              id: repo-owner
              run: |
                REPO_OWNER=${{ github.repository_owner }}
                echo "::set-output name=repo-owner::${REPO_OWNER,,}"
            - name: Build all Docker images
              run: |
                rootdir="$(pwd)"
                for d in $(ls | sort -h -r); do
                    if [ -d "$d" ]; then
                        cd "$d"
                        program=$(echo "$d" | cut -d: -f 1)
                        if ! grep -Fxq "$program" "$built"; then
                            # No version built yet
                            if [ -f Dockerfile ]; then
                                # The directory name *is* the tag and version
                                docker build --tag ${{ steps.repo-owner.outputs.repo-owner }}/$d .
                                docker push ${{ steps.repo-owner.outputs.repo-owner }}/$d
                            fi
                        fi
                    fi
                done
