name: Publish Documentation

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          VERSION=$(date +%s)
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build . --file Dockerfile --tag leticiamaria/app:${VERSION}
          docker push leticiamaria/app:${VERSION}

